HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

setopt appendhistory autocd notify
unsetopt beep
bindkey -v

autoload -Uz compinit promptinit
compinit
prompt pure

#source ./plugins/extract.plugin.zsh

alias vf="vim $(fzf)"
alias v="vim"
alias c="clear"
